---
- name: Create config directories for containerd and kata-containers
  file: 
    path: "/etc/{{ item }}"
    state: directory
  loop:
    - containerd
    - kata-containers

- name: Copy default configuration to /etc if file does not exist
  copy:
    src: /usr/share/defaults/kata-containers/configuration.toml
    dest: /etc/kata-containers/config.toml
    remote_src: yes
    force: no

- name: Configure containerd to use kata-runtime
  copy:
    dest: /etc/containerd/config.toml
    content: |
      [plugins]
        [plugins.cri]
          [plugins.cri.containerd]
            [plugins.cri.containerd.default_runtime]
              runtime_type = "io.containerd.kata.v2"

            [plugins.cri.containerd.runtimes.kata]
              runtime_type = "io.containerd.kata.v2"
              [plugins.cri.containerd.runtimes.kata.options]
                ConfigPath = "/etc/kata-containers/config.toml"

          [plugins.cri.cni]
            # conf_dir is the directory in which the admin places a CNI conf.          
            conf_dir = "/etc/cni/net.d"

          [plugins."io.containerd.grpc.v1.cri".containerd]
            default_runtime_name = "kata"

- name: Restarting containerd
  service:
    name: containerd
    enabled: yes
    state: restarted