---
- name: Create config directories for containerd and kata-containers
  file: 
    path: "/etc/{{ item }}"
    state: directory
  loop:
    - containerd
    - kata-containers

- name: Copy default configuration to /etc if file does not exist
  copy:
    src: /usr/share/defaults/kata-containers/configuration.toml
    dest: /etc/kata-containers/config.toml
    remote_src: yes
    force: no

- name: Configure containerd to use kata-runtime
  copy:
    src: "{{ role_path }}/files/config.toml"
    dest: /etc/containerd/config.toml    


- name: Restarting containerd
  service:
    name: containerd
    enabled: yes
    state: restarted
  changed_when: False