---
- name: Update and upgrade all servers, set time, disable swap
  hosts: all
  roles: 
    - update_upgrade
    - timezone
    - disable_swap 

- name: Repair shitty ansible file that is broke because it sucks
  hosts: k8smaster
  roles:
    - repair_shitty_ansible_file

- name: Install Kata Containers
  hosts: k8sworker
  roles:
    - install_kata

- name: Install containerd
  hosts: all
  roles:
    - install_containerd

- name: Configure containerd
  hosts: k8sworker
  roles:
    - configure_containerd

- name: setup cni_plugins
  hosts: all
  roles:
    - cni_plugins

- name: Install Kuberbetes tools
  hosts: all
  roles:
    - kubetools

- name: Master setup
  hosts: k8smaster
  roles:
    - master_setup

- name: Join Cluster
  hosts: k8sworker
  roles:
    - join
    





