---
- name: Update and upgrade all servers, set time, disable swap
  hosts: all
  roles: 
    - base

- name: Install Kata Containers
  hosts: k8sworker
  roles:
    - install_kata

- name: Install containerd
  hosts: all
  roles:
    - install_containerd

- name: Configure containerd
  hosts: k8sworker
  roles:
    - role: configure_containerd
      tags: containerd

- name: setup cni_plugins and kubetools
  hosts: all
  roles:
    - cni_plugins
    - kubetools

- name: Master setup
  hosts: k8smaster
  roles:
    - master_setup

- name: Join Cluster
  hosts: k8sworker
  roles:
    - role: join_nodes
      tags: join_tag

- name: Standart Kubernetes Setup
  hosts: k8smaster
  roles:
    - role: cilium_networking
      tags: networking
    - role: dashboard
      tags: dashboard
    - role: storage
      tags: storage
    - role: ingress
      tags: ingress
    





