---
- name: Update and upgrade all servers, set time, disable swap
  hosts: all
  roles: 
    - base

- name: Install Kata Containers
  hosts: worker
  roles:
    - install_kata

- name: Install containerd
  hosts: all
  roles:
    - install_containerd

- name: Configure containerd
  hosts: worker
  roles:
    - role: configure_containerd
      tags: containerd

- name: setup cni_plugins and kubetools
  hosts: all
  roles:
    - cni_plugins
    - kubetools

- name: Master setup
  hosts: master
  roles:
    - master_setup

- name: Join Cluster
  hosts: worker
  roles:
    - role: join_nodes
      tags: join_tag

- name: Standart Kubernetes Setup
  hosts: master
  roles:
    - role: flannel_networking
      tags: networking
    - role: dashboard
      tags: dashboard
    - role: storage
      tags: storage
    - role: ingress
      tags: ingress
    - role: webapp_kata
      tags: kata-test
    





