---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: default
  selfLink: /api/v1/namespaces/default/services/traefik
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      nodePort: 0
      targetPort: web
    - name: websecure
      protocol: TCP
      port: 443
      nodePort: 0
      targetPort: websecure
    - name: traefik
      protocol: TCP
      port: 9000
      targetPort: traefik
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: ClusterIP
  externalIPs:
    - 10.10.6.60
  sessionAffinity: None
