---

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: install apt-transport-https and pip
  apt:
    name: ['apt-transport-https', 'python3-pip']
    state: latest

- name: install pip libaries for k8s managed ansible
  pip:
    name:
      - openshift  
      - pyyaml
      - kubernetes
      - pyhelm

- name: add helm repo
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: apt update
  apt:
    state: latest
    upgrade: dist
    update_cache: yes

- name: install helm to manage deployments
  apt:
    name: helm
    state: latest

- name: add longhorn repo
  git:
    repo: https://github.com/longhorn/longhorn
    dest: /home/alberto/longhorn

- name: add longhorn namespace
  become_user: alberto
  k8s:
    name: longhorn-system
    api_version: v1
    kind: Namespace
    state: present

- name: deploy longhorn via helm
  become_user: alberto
  register: out
  failed_when: >
    !("re-use" in out.stderr) and
    (out.stderr != '')
  command: |
    helm install longhorn /home/alberto/longhorn/chart/ --namespace longhorn-system

- name: deploy traefik via helm
  become_user: alberto
  helm:
    host: localhost
    chart:
      name: traefik
      source:
        type: repo
        location: "https://containous.github.io/traefik-helm-chart"
    state: present
    name: traefik
    namespace: traefik