version = 2

[grpc]
  gid = 1000

[plugins."io.containerd.grpc.v1.cri"]
  [plugins."io.containerd.grpc.v1.cri".containerd]
    #default_runtime_name = "kata"
    no_pivot = false

    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
      runtime_type = "io.containerd.kata.v2"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
        ConfigPath = "/etc/kata-containers/config.toml"

    [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
      # runtime_type is the runtime type to use in containerd e.g. io.containerd.runtime.v1.linux
      runtime_type = "io.containerd.runtime.v1.linux"

      # runtime_engine is the name of the runtime engine used by containerd.
      runtime_engine = "/usr/bin/kata-runtime"

      # To enable networking for the workloads run by Kata, CRI-O needs to be configured to manage network namespaces, by setting the following key to true.
      manage_ns_lifecycle = true
