---

- name: copy manifest files for ingress configuration
  synchronize:
    src: "{{ role_path }}/files/"
    dest: "/home/alberto/k8s/" 

- name: install ingress-nginx 
  become_user: alberto
  command: |
    kubectl apply -f /home/alberto/k8s/ingress_nginx.yaml

- name: setup k8s-dashboard ingress
  become_user: alberto
  command: |
    kubectl apply -f /home/alberto/k8s/k8s_dashboard_ingress.yml
  
