apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      annotations: 
        io.kubernetes.cri.untrusted-workload: "true"
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: robbmue/webapi
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapi-ingress
  namespace: default
spec:
  rules:
  - host: webapi.k8smaster      
    http:
      paths:
      - path: /
        backend:
          serviceName: webapi-service
          servicePort: web
  tls:
  - hosts:
      - webapi.k8smaster
    secretName: webapi-tls-cert

---
apiVersion: v1
kind: Secret
metadata: 
  name: webapi-tls-cert
  namespace: default
type: kubernetes.io/tls
data: 
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMmJNTS9RYk13QVdGNks1Yno5ZFIyekwxYlVyWXgxY0J3dHdDSTVVK0o4a0JhbTRxCjRKRWtXVUNUcGN6REl5aGVCNFBJTGVuSVJxRU5YL0xvN05KRFFtaEVrVUtKWkdhZXEzc3loc1dNSXI2OVlCaHkKWC9McUJya1pEdUNJdVdnLytQZXdzVzJ1Z3c1a1FmU3E2SFVyYjNrRFkvU1QrMHJKMDdlMUZOVGIyQTROcTZGcAppdDVyOXZPOUh0ZDVwWVhKNFNucTBoUjRZcm90dzBaSWpEN0Vxa2VzeHV4V2V6OVZkTjNvaWNlUjJvYS81S0cwCnFkSmc5ZmZ3eDRWc2draENmbGRjWGxIL25TNVczOVJDOS9zMWtIenRjY3c0RWJxSE1RSlhOaGd5RDJGQVpGWmQKeWNVTWhDMDBiVTJiL25YS1NCWDFrQlphSlIvRit6QlJwV1BKSndJREFRQUJBb0lCQVFDWVdNUURJa29SS3d4TwpEQTYyUVlISU96NGprTmhwajhyc3VaaEpuSHlWelFYUG5HOG5Ib3RvWmxldEZNR09qZ1pYamZKOXB2Zi83VjcxCndZRWRrZnQ5c29naGU0VzRuRlAzdjB4Wm9rOXlWVGNqMDVmZTY1aTR3Ym4yZmsxUUt0TnlBS3hIVG5Gc3g1cUQKeVp2ODkxcEJOVmVaRUtTcW0ram4zOHk2V2tmTFJxZ0IxTjZOQVVGT1IyOG0wWUxmekhHUmZpSTdxam5MZkhrZApmNGY5WTdINEgxMWdFL0NGbVVnSVQ5c093LzFzbndVbzVqd3BCZUhCbGtUdnEwMi91bG9TeTdaMHdyQUZ0aWRjCmlyNUQxVzk4eVNIUFdVVHNvNnpYaU1IOUpHSnplZ3J5eGlSU3ZzWWZMRUphejg3QXNWcFFYRjU1aVhXeHZ2RmcKL2hPNm9IaVJBb0dCQU94c1drSm1ONGl0Mmp5WkVqVzdtVE9mOUI1MzRNQk1sVnI0ck83SXpNQjhTdUZocCtVVgpHTDRabkVER3dQMGQvV01Ecm1iOUxJeFhvN2x3V01RVGhqaVdGOFQ1Z0NTOUJPdlRING1iaGtlS1FIa2dMYzAwCkJ2T0pZaG1XQ2JGYWpyYnVkY2JMWEtDQXVpNGlSelFjNGRjRkFaT0kxQWU4eXo1N2xISjFCVkR2QW9HQkFPdTUKeTJKMDNxQlp4NVNkb29PemlkdmR3U3JOeHU2WVJDZ1F1ek9vRzNaWWw0RHViREFhNzhCdmZjT2Ntd3BKWVhXZQpMWjlHSHNwUDBJeDhmTnNDY1JlSmlYTHJYL1FBdXhrbUl1Q1FsbFhXL095U1F2MnVIT2kxc0ZkbkdQTGJFOTFNCi9XUStpdTlwQ3ROTmM4U0ZLNElrVytNaG5IN0pvUm10Rk9OQkVadEpBb0dCQU9xWitsYTVKNUl4TWNXLy94bmkKdGZ0TVZlbUYremZXeHI0bTFUTjlmZS9qWmtxUHBSTGxCRkJmQ1hZZHc1Tm9GdkFSenhYVFZFbFBEZUFOWTRmdAo5OXBlMWVkWHpaaW5HQ01LdE5qUHcwZHFJT0FRMW1JeHBsUXpsMnpjUFhJSDhtWUQ2a3NCc1VCemZFd2JKNXpHCnJETzVlLzd5WDdQdDI2Qjg4S2xEQmF0eEFvR0FESGFKUzA1VWl2UFVPb1pQRmxtQ3UyNHhEVnROM2tXTXJQV2QKZ0RDdUt3YXFFL1lISUUvOFJ4ZGQ5ZDZzejlGclpyV1RRZTJLS1RZcEY1UnBZWWJ5aGNVTzBGV2pnQm9keWttYQo1SGFnakM5T3RnOVJuV244TzAySDRrY2dLWTd0c1BDbUlRdXhldEQ1OG93UXg5NG1tNzNpWWRMZ0hFLzZ4WW5DCkpmWEZ3WWtDZ1lBU2ZpUzVtdW1PSXhiMkF2RTRjaUJSNUJ1U0c5Z3ZsYVdReGxUSW5PY3lYY3hvYU5BOGozNmcKWWM2NE80UWplUG9yM1FBcW9EVnB0VGN5dCt3clVHN1ZjWjVUWkMwYTRYSUtidWgzSUtHd2xVRmo2YythOExPdAp2SHpxVE1aMjBXdVJLcHF3dEE0bXVNb1JpNG12NFRXQTVSSmhtVS9rR2pUeDdocTBHRG1WQmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyRENDQWNDZ0F3SUJBZ0lKQU5obHhOL1BDby84TUEwR0NTcUdTSWIzRFFFQkJRVUFNQnN4R1RBWEJnTlYKQkFNVEVIZGxZbUZ3YVM1ck9ITnRZWE4wWlhJd0hoY05NakF3T0RFeE1URTFOekl5V2hjTk16QXdPREE1TVRFMQpOekl5V2pBYk1Sa3dGd1lEVlFRREV4QjNaV0poY0drdWF6aHpiV0Z6ZEdWeU1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTJiTU0vUWJNd0FXRjZLNWJ6OWRSMnpMMWJVcll4MWNCd3R3Q0k1VSsKSjhrQmFtNHE0SkVrV1VDVHBjekRJeWhlQjRQSUxlbklScUVOWC9MbzdOSkRRbWhFa1VLSlpHYWVxM3N5aHNXTQpJcjY5WUJoeVgvTHFCcmtaRHVDSXVXZy8rUGV3c1cydWd3NWtRZlNxNkhVcmIza0RZL1NUKzBySjA3ZTFGTlRiCjJBNE5xNkZwaXQ1cjl2TzlIdGQ1cFlYSjRTbnEwaFI0WXJvdHcwWklqRDdFcWtlc3h1eFdlejlWZE4zb2ljZVIKMm9hLzVLRzBxZEpnOWZmd3g0VnNna2hDZmxkY1hsSC9uUzVXMzlSQzkvczFrSHp0Y2N3NEVicUhNUUpYTmhneQpEMkZBWkZaZHljVU1oQzAwYlUyYi9uWEtTQlgxa0JaYUpSL0YrekJScFdQSkp3SURBUUFCb3g4d0hUQWJCZ05WCkhSRUVGREFTZ2hCM1pXSmhjR2t1YXpoemJXRnpkR1Z5TUEwR0NTcUdTSWIzRFFFQkJRVUFBNElCQVFERWc3Qi8KNmI0R2Fiem93N3BJV2p3WE1vOUh5UFhLTWlvaFBFdmhLanpNQ3FVNlAwZEZUSzh3emhYdy81YjFjZmxncTVNegpYQTlQejh0UzErMS9sL0VuUW0vTG5IaUUyY2tSWDQ5dWJwdWNCTk0yVGt3TldjTmJ3SUt0RmlsdDRTUFBpWmJpCkF5R0pPaU5yVjE4Z09aVElTVUpXKzZaeXdzTzVSNGIzUUh2QlpUVnpJcjJrcXdyN3Y4cVFpem9Ma0lZTk1aaGcKYTR3TUNDNHh0V3BYU2JRZmFyUzdtRldyYnY5b3FUZHNSQ2xQTHVVcXhPaitORHY4RTBJMjB6NDlPaFB0WVpUQwpjeW40T0Fpb3l1enhiRklobVI3T1NyZGhSMTJMQ1RnNVNlV0NVVmlQRVBmWTRmaStpTTM5K0UrVjhHckJOdU5JClFtMFRYT1U4bEUxYnpIS08KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
