---

- name: Installation of tools
  apt:
    name: "{{ item }}"
    state: latest
  loop: 
    - kubelet
    - kubeadm
    - kubectl

- name: Set ip tables to legacy
  command: update-alternatives --set {{ item }} /usr/sbin/{{ item }}-legacy
  loop:
    - iptables
    - ip6tables
    - arptables 
    - ebtables 