---

- name: Installation of tools
  apt:
    name: "{{ item }}"
    state: latest
  loop: 
    - kubelet=1.18.6-00
    - kubeadm
    - kubectl

- name: modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present
