---

- name: set scrctl config to have debugging tools for kubernetes on master
  copy:
    src: "{{ role_path }}/files/crictl.yaml"
    dest: /etc/crictl.yaml

- name: is already insalled check
  command: |
    kubectl get nodes
  register: get_nodes

- include_tasks:
    - reset_master.yml
  when: not get_nodes.stdout

- name: Initialize cluster with kubeadm
  command: |
    /usr/bin/kubeadm init \
    --pod-network-cidr 10.244.0.0/16 \
    --apiserver-advertise-address 192.168.0.1 \
    --apiserver-cert-extra-sans {{ extra_sans }} \
    --token-ttl 24h0m0s \
    --token {{ token }}

