---

- name: set scrctl config to have debugging tools for kubernetes on master
  copy:
    src: "{{ role_path }}/files/crictl.yaml"
    dest: /etc/crictl.yaml

- name: check if kubelet file exists
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: reset kubernetes status
  include: reset_master.yml
  when: kubelet_conf.stat.exists == True

- name: Initialize cluster with kubeadm
  command: |
    /usr/bin/kubeadm init \
    --pod-network-cidr 10.244.0.0/16 \
    --apiserver-advertise-address 192.168.0.1 \
    --apiserver-cert-extra-sans {{ extra_sans }} \
    --token-ttl 24h0m0s \
    --token {{ token }}

- name: setup config for alberto
  become: no
  command: |
    mkdir -p $HOME/.kube  \
    && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config \
    && sudo chown $(id -u):$(id -g) $HOME/.kube/config

