---

- name: Initialize cluster with kubeadm
  command: |
    /usr/bin/kubeadm init \
    --pod-network-cidr 10.244.0.0/16 \
    --apiserver-advertise-address 192.168.0.1 \
    --apiserver-cert-extra-sans {{ extra_sans }} \
    --token-ttl 24h0m0s \
    --token {{ token }}

