---

- name: remoce kubernetes first
  command: |
    kubeadm reset

- name: stop all running containers
  command: |
   crictl stop $(crictl ps -a -q)

- name: remove all existing containes
  command: |
    crictl rm $(crictl ps -a -q) 

- name: reset iptables
  systemd:
    name: netfilter-persistent
    state: restarted

    